version: "3.8"
services:
  api:
    build: ./
    ports:
      - 8000:8000
    networks:
      - go-api
    volumes:
      - ./:/app
    logging:
      options:
        max-size: 10m
        max-file: "10"

networks:
  go-api:
    
